# Generated by Django 4.1.7 on 2023-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetData',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('cost_usd', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('cost_rub', models.DecimalField(decimal_places=4, max_digits=100)),
            ],
        ),
    ]
